### ISSUE TITLE
Is our WMS usable in AGOL? HTTPS issue?

### ISSUE THREAD

**Issue by completer** [jncc/dnode#9]

**Comment by completer** [comment]
I created an ArcGIS Online account, and using

    https://eo.jncc.gov.uk/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities

gives the error:

> Error: The WMS service, https://eo.jncc.gov.uk/geoserver/ows?version=1.1.1, cannot be added to the map. It is either not available or you have entered an invalid URL for the type of layer you want to reference.

Removing the `s` and using `http` seems to work fine.

**Comment by paul-gilbertson** [comment]
HTTPS unusable due to browser cross-origin (CORS) restrictions. No fix possible, above work around should be fine.

**Comment by mattdebont** [comment]
Going to assume this ticket is dead
